feature_extraction:
  name: pyannote.models.DeviNet
  params:
    conv_blocks: 3
    conv_channels: 128
    layers_pooling: [2, 2, 2 ,2]
    final_pooling: 4
    dropout: 0.3
    recurrent: [128]
    gated_rnn: True
    linear_layers: [32, 32]